name:                aeson-via
version:             0.1.0
github:              "ejconlon/aeson-via"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2020 Eric Conlon"
category:            Data
synopsis:            Wrappers to derive-via Aeson ToJSON/FromJSON typeclasses

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/aeson-via#readme>

dependencies:
- base >= 4.12 && < 5
- aeson >= 1.4
- aeson-casing >= 0.2
- newtype-generics >= 0.5
- text >= 1.2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src
