name:                aeson-via
version:             0.2.1
github:              "ejconlon/aeson-via"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2020 Eric Conlon"
category:            Data
synopsis:            Wrappers to derive-via Aeson ToJSON/FromJSON typeclasses

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/aeson-via#readme>

dependencies:
- base >= 4.12 && < 5
- aeson >= 2.0 && < 2.2
- aeson-casing >= 0.2 && < 0.3
- newtype-generics >= 0.5 && < 0.7
- text >= 1.2 && < 2.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src

tests:
  aeson-via-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson-via
    - tasty >= 1.2 && < 1.5
    - tasty-hunit >= 0.10 && < 0.11
